### ISSUE TITLE
battery.sh cannot find i2c-tools

### ISSUE THREAD

**Issue by Mirppc** [NextThingCo/CHIP-hwtest#6]
i am having an issue executing the battery.sh

When i do i get an error...
chip@chip:~$ battery.sh
/usr/bin/battery.sh: line18: i2cset: command not found
/usr/bin/battery.sh: line22: i2cget: command not found
/usr/bin/battery.sh: line25: &0x02: syntax error: operand expected (errpr token is "&0x02")
chip@chip:~$ sudo apt-get install i2c-tools
<redacted as i am not copying and pasting via RDP>
i2c-tools is already the newest version.

Ponderous what the issue is and how to resolve it as i just picked up a battery and dont know if it is any good.  I dont have any other means of testing it.

**Comment by computermouth** [comment]
Hi Mirppc,

Currently you have to run battery.sh as sudo. Although, you may be able to drop the sudo if you add /usr/sbin to your path, and add the user chip to the `i2c` group.

-- Ben

**Comment by Mirppc** [comment]
Worked like a charm!
